export interface PFProductNotes {
  top: string[];
  middle: string[];
  base: string[];
}

export interface PFProduct {
  id: string;
  slug: string;
  name: string;
  scent: string;
  category: 'Air Freshener' | 'Incense' | 'Candle' | 'Room Spray';
  tagline: string;
  description: string;
  notes: PFProductNotes;
  imageUrl: string;
  inStock: boolean;
  ingredients: string;
  howToUse: string[];
  scentThrow: string;
  specs?: string[];
}

export const pfProducts: PFProduct[] = [
  // Air Fresheners
  {
    id: 'af-amber-moss',
    slug: 'amber-moss-air-freshener',
    name: 'Amber & Moss',
    scent: 'Amber & Moss',
    category: 'Air Freshener',
    tagline: 'Earthy, woody, fresh',
    description: 'A weekend in the mountains, sun gleaming through the canopy.',
    notes: {
      top: ['Moss', 'Lavender'],
      middle: ['Sage', 'Orange', 'Lavandin'],
      base: ['Amber', 'Musk'],
    },
    imageUrl: '/images/PF Candle Co/amber-moss-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-golden-coast',
    slug: 'golden-coast-air-freshener',
    name: 'Golden Coast',
    scent: 'Golden Coast',
    category: 'Air Freshener',
    tagline: 'Fresh, coastal, aromatic',
    description: 'Big Sur magic, wild sage baking in the sun, the rumble of waves and rocks.',
    notes: {
      top: ['Eucalyptus', 'Sea Salt'],
      middle: ['Redwood'],
      base: ['Palo Santo', 'Sage'],
    },
    imageUrl: '/images/PF Candle Co/golden-coast-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-los-angeles',
    slug: 'los-angeles-air-freshener',
    name: 'Los Angeles',
    scent: 'Los Angeles',
    category: 'Air Freshener',
    tagline: 'Bright, citrus, floral',
    description: 'Overstated inspiration, a wave of salt and sandal, lemon and musk.',
    notes: {
      top: ['Redwood', 'Lime'],
      middle: ['Jasmine', 'Yarrow'],
      base: ['Musk'],
    },
    imageUrl: '/images/PF Candle Co/los-angeles-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-ojai-lavender',
    slug: 'ojai-lavender-air-freshener',
    name: 'Ojai Lavender',
    scent: 'Ojai Lavender',
    category: 'Air Freshener',
    tagline: 'Aromatic, citrus, fresh',
    description: 'Sun-drenched fields, orange groves and lavender farms, jagged mountains washed in a rosy, sunset glow.',
    notes: {
      top: ['Pixie Tangerine', 'Bergamot', 'Eucalyptus'],
      middle: ['Lavender', 'Rose', 'Lily'],
      base: ['Mint', 'Red Cedar'],
    },
    imageUrl: '/images/PF Candle Co/ojai-lavender-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-pinon',
    slug: 'pinon-air-freshener',
    name: 'Piñon',
    scent: 'Piñon',
    category: 'Air Freshener',
    tagline: 'Woody, smoky, warm',
    description: 'Winters in the Southwest, piñon logs burning in terracotta, glowing embers, cedar, vetiver.',
    notes: {
      top: ['Pine', 'Cedar'],
      middle: ['Smoke'],
      base: ['Vanilla', 'Vetiver'],
    },
    imageUrl: '/images/PF Candle Co/pinon-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-teakwood-tobacco',
    slug: 'teakwood-tobacco-air-freshener',
    name: 'Teakwood & Tobacco',
    scent: 'Teakwood & Tobacco',
    category: 'Air Freshener',
    tagline: 'Woody, warm, musky',
    description: 'The one that started it all. Some call it the boyfriend scent, we call it the O.G.',
    notes: {
      top: ['Orange', 'Leather'],
      middle: ['Black Tea', 'Pepper', 'Tobacco Leaf'],
      base: ['Sandalwood', 'Teak', 'Patchouli', 'Musk', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/teakwood-tobacco-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },
  {
    id: 'af-wild-herb-tonic',
    slug: 'wild-herb-tonic-air-freshener',
    name: 'Wild Herb Tonic',
    scent: 'Wild Herb Tonic',
    category: 'Air Freshener',
    tagline: 'Aromatic, crisp, herbaceous',
    description: 'Barefoot walks through wild herb gardens, cool mountain air, summer rosé.',
    notes: {
      top: ['Lavender', 'Mint'],
      middle: ['Basil', 'Rosemary'],
      base: ['Cedar', 'Eucalyptus'],
    },
    imageUrl: '/images/PF Candle Co/wild-herb-tonic-af.jpg',
    inStock: true,
    ingredients: 'Phthalate-free fragrance oil blend on recycled paper pulp.',
    howToUse: [
      'Hang your air freshener anywhere you need a burst of fragrance - car, closet, office, or bedroom.',
      'To refresh the scent, give the freshener a gentle squeeze.',
      'Lasts 2-4 weeks depending on environment and use.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
  },

  // Incense
  {
    id: 'in-amber-moss',
    slug: 'amber-moss-incense',
    name: 'Amber & Moss',
    scent: 'Amber & Moss',
    category: 'Incense',
    tagline: 'Earthy, woody, fresh',
    description: 'A weekend in the mountains, sun gleaming through the canopy.',
    notes: {
      top: ['Moss', 'Lavender'],
      middle: ['Sage', 'Orange', 'Lavandin'],
      base: ['Amber', 'Musk'],
    },
    imageUrl: '/images/PF Candle Co/amber-moss-incense.jpg.webp',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-blonde-hinoki',
    slug: 'blonde-hinoki-incense',
    name: 'Blonde Hinoki',
    scent: 'Blonde Hinoki',
    category: 'Incense',
    tagline: 'Woody, clean, fresh',
    description: 'Pale wood, green cypress, earthy cedar.',
    notes: {
      top: ['Hinoki', 'Cypress'],
      middle: ['Cedar'],
      base: ['Vetiver', 'Oakmoss'],
    },
    imageUrl: '/images/PF Candle Co/blonde-hinoki-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-golden-coast',
    slug: 'golden-coast-incense',
    name: 'Golden Coast',
    scent: 'Golden Coast',
    category: 'Incense',
    tagline: 'Fresh, coastal, aromatic',
    description: 'Big Sur magic, wild sage baking in the sun, the rumble of waves and rocks.',
    notes: {
      top: ['Eucalyptus', 'Sea Salt'],
      middle: ['Redwood'],
      base: ['Palo Santo', 'Sage'],
    },
    imageUrl: 'https://pfcandleco.com/cdn/shop/products/IN21.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-milky-santal',
    slug: 'milky-santal-incense',
    name: 'Milky Santal',
    scent: 'Milky Santal',
    category: 'Incense',
    tagline: 'Creamy, woody, warm',
    description: 'Soft sandalwood, warm vanilla, creamy musk.',
    notes: {
      top: ['Sandalwood'],
      middle: ['Vanilla', 'Coconut'],
      base: ['Amber', 'Musk'],
    },
    imageUrl: '/images/PF Candle Co/milky-santal.jpg.webp',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-ojai-lavender',
    slug: 'ojai-lavender-incense',
    name: 'Ojai Lavender',
    scent: 'Ojai Lavender',
    category: 'Incense',
    tagline: 'Aromatic, citrus, fresh',
    description: 'Sun-drenched fields, orange groves and lavender farms, jagged mountains washed in a rosy, sunset glow.',
    notes: {
      top: ['Pixie Tangerine', 'Bergamot', 'Eucalyptus'],
      middle: ['Lavender', 'Rose', 'Lily'],
      base: ['Mint', 'Red Cedar'],
    },
    imageUrl: '/images/PF Candle Co/ojai-lavender-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-pinon',
    slug: 'pinon-incense',
    name: 'Piñon',
    scent: 'Piñon',
    category: 'Incense',
    tagline: 'Woody, smoky, warm',
    description: 'Winters in the Southwest, piñon logs burning in terracotta, glowing embers, cedar, vetiver.',
    notes: {
      top: ['Pine', 'Cedar'],
      middle: ['Smoke'],
      base: ['Vanilla', 'Vetiver'],
    },
    imageUrl: '/images/PF Candle Co/pinon-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-plush-vetiver',
    slug: 'plush-vetiver-incense',
    name: 'Plush Vetiver',
    scent: 'Plush Vetiver',
    category: 'Incense',
    tagline: 'Earthy, soft, woody',
    description: 'Soft suede, earthy vetiver, smoked cedar.',
    notes: {
      top: ['Vetiver'],
      middle: ['Suede', 'Leather'],
      base: ['Cedar', 'Smoke'],
    },
    imageUrl: '/images/PF Candle Co/plush-vetiver-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-smoked-cherry',
    slug: 'smoked-cherry-incense',
    name: 'Smoked Cherry',
    scent: 'Smoked Cherry',
    category: 'Incense',
    tagline: 'Fruity, warm, smoky',
    description: 'Dark cherry, smoked wood, rich vanilla.',
    notes: {
      top: ['Cherry'],
      middle: ['Smoke', 'Wood'],
      base: ['Vanilla', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/smoked-cherry-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-tuberose-musk',
    slug: 'tuberose-musk-incense',
    name: 'Tuberose Musk',
    scent: 'Tuberose Musk',
    category: 'Incense',
    tagline: 'Floral, musky, soft',
    description: 'White tuberose, soft musk, blonde woods.',
    notes: {
      top: ['Tuberose'],
      middle: ['Musk', 'Jasmine'],
      base: ['Blonde Woods', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/tuberose-musk-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },
  {
    id: 'in-wild-herb-tonic',
    slug: 'wild-herb-tonic-incense',
    name: 'Wild Herb Tonic',
    scent: 'Wild Herb Tonic',
    category: 'Incense',
    tagline: 'Aromatic, crisp, herbaceous',
    description: 'Barefoot walks through wild herb gardens, cool mountain air, summer rosé.',
    notes: {
      top: ['Lavender', 'Mint'],
      middle: ['Basil', 'Rosemary'],
      base: ['Cedar', 'Eucalyptus'],
    },
    imageUrl: '/images/PF Candle Co/wild-herb-tonic-incense.jpg',
    inStock: true,
    ingredients: 'Charcoal based incense sticks and phthalate-free fine fragrance oil. Hand-dipped in our Los Angeles factory.',
    howToUse: [
      'Light the end of the incense, and allow the flame to burn for approximately 10-15 seconds.',
      'Blow on the flame to extinguish. The incense should produce a glowing red ember and a tendril of smoke, and will continue to burn on its own.',
      'Burn incense on a heatproof, non-flammable holder only.',
      'Burn incense in a well-ventilated room, away from flammable materials, and never leave incense burning unattended or near children, pets, or a draft.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['15 charcoal-based incense sticks', 'One hour burn time per stick', 'Hand-dipped in Los Angeles', 'Sticks measure 10.75" in length'],
  },

  // 24 oz Candles
  {
    id: 'candle-arroyo-oak',
    slug: 'arroyo-oak-candle',
    name: 'Arroyo Oak',
    scent: 'Arroyo Oak',
    category: 'Candle',
    tagline: 'Earthy, woody, fresh',
    description: 'California oaks in sunlight, warm vetiver, earthy frankincense.',
    notes: {
      top: ['Vetiver', 'Frankincense'],
      middle: ['California Oak'],
      base: ['Cedarwood', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/arroyo-oak-candle.jpg',
    inStock: true,
    ingredients: 'Made in our California factory using 100% domestically-grown soy wax, fine fragrance oils, and cotton-core wicks. Fragrances are phthalate-free and never tested on animals.',
    howToUse: [
      'Trim wick to 1/4" before each lighting.',
      'Allow the wax to melt to the edges of the jar during each burn to prevent tunneling.',
      'Do not burn for more than 4 hours at a time.',
      'Stop burning your candle when only 1/4" of wax remains.',
      'Never leave a candle burning unattended, near a draft, or in reach of children or pets.',
      'Protect surface underneath the candle.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['24 oz candle', '100% soy wax', '100+ hour burn time', 'Hand-poured in Los Angeles', 'Amber glass jar with brass lid'],
  },
  {
    id: 'candle-pinon',
    slug: 'pinon-candle',
    name: 'Piñon',
    scent: 'Piñon',
    category: 'Candle',
    tagline: 'Woody, smoky, warm',
    description: 'Winters in the Southwest, piñon logs burning in terracotta, glowing embers, cedar, vetiver.',
    notes: {
      top: ['Pine', 'Cedar'],
      middle: ['Smoke'],
      base: ['Vanilla', 'Vetiver'],
    },
    imageUrl: '/images/PF Candle Co/pinon-candle.jpg',
    inStock: true,
    ingredients: 'Made in our California factory using 100% domestically-grown soy wax, fine fragrance oils, and cotton-core wicks. Fragrances are phthalate-free and never tested on animals.',
    howToUse: [
      'Trim wick to 1/4" before each lighting.',
      'Allow the wax to melt to the edges of the jar during each burn to prevent tunneling.',
      'Do not burn for more than 4 hours at a time.',
      'Stop burning your candle when only 1/4" of wax remains.',
      'Never leave a candle burning unattended, near a draft, or in reach of children or pets.',
      'Protect surface underneath the candle.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['24 oz candle', '100% soy wax', '100+ hour burn time', 'Hand-poured in Los Angeles', 'Amber glass jar with brass lid'],
  },
  {
    id: 'candle-sweet-grapefruit',
    slug: 'sweet-grapefruit-candle',
    name: 'Sweet Grapefruit',
    scent: 'Sweet Grapefruit',
    category: 'Candle',
    tagline: 'Bright, citrus, fresh',
    description: 'Ripe grapefruit, lily of the valley, and coriander blossom.',
    notes: {
      top: ['Grapefruit'],
      middle: ['Lily of the Valley', 'Coriander Blossom'],
      base: ['Vetiver'],
    },
    imageUrl: '/images/PF Candle Co/sweet-grapefruit-candle.jpg',
    inStock: true,
    ingredients: 'Made in our California factory using 100% domestically-grown soy wax, fine fragrance oils, and cotton-core wicks. Fragrances are phthalate-free and never tested on animals.',
    howToUse: [
      'Trim wick to 1/4" before each lighting.',
      'Allow the wax to melt to the edges of the jar during each burn to prevent tunneling.',
      'Do not burn for more than 4 hours at a time.',
      'Stop burning your candle when only 1/4" of wax remains.',
      'Never leave a candle burning unattended, near a draft, or in reach of children or pets.',
      'Protect surface underneath the candle.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['24 oz candle', '100% soy wax', '100+ hour burn time', 'Hand-poured in Los Angeles', 'Amber glass jar with brass lid'],
  },
  {
    id: 'candle-teakwood-tobacco',
    slug: 'teakwood-tobacco-candle',
    name: 'Teakwood & Tobacco',
    scent: 'Teakwood & Tobacco',
    category: 'Candle',
    tagline: 'Woody, warm, musky',
    description: 'The one that started it all. Some call it the boyfriend scent, we call it the O.G.',
    notes: {
      top: ['Orange', 'Leather'],
      middle: ['Black Tea', 'Pepper', 'Tobacco Leaf'],
      base: ['Sandalwood', 'Teak', 'Patchouli', 'Musk', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/teakwood-tobacco-candle.jpg',
    inStock: true,
    ingredients: 'Made in our California factory using 100% domestically-grown soy wax, fine fragrance oils, and cotton-core wicks. Fragrances are phthalate-free and never tested on animals.',
    howToUse: [
      'Trim wick to 1/4" before each lighting.',
      'Allow the wax to melt to the edges of the jar during each burn to prevent tunneling.',
      'Do not burn for more than 4 hours at a time.',
      'Stop burning your candle when only 1/4" of wax remains.',
      'Never leave a candle burning unattended, near a draft, or in reach of children or pets.',
      'Protect surface underneath the candle.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['24 oz candle', '100% soy wax', '100+ hour burn time', 'Hand-poured in Los Angeles', 'Amber glass jar with brass lid'],
  },

  // Room Sprays
  {
    id: 'spray-golden-coast',
    slug: 'golden-coast-room-spray',
    name: 'Golden Coast',
    scent: 'Golden Coast',
    category: 'Room Spray',
    tagline: 'Fresh, coastal, aromatic',
    description: 'Big Sur magic, wild sage baking in the sun, the rumble of waves and rocks.',
    notes: {
      top: ['Eucalyptus', 'Sea Salt'],
      middle: ['Redwood'],
      base: ['Palo Santo', 'Sage'],
    },
    imageUrl: '/images/PF Candle Co/golden-coast-spray.jpg',
    inStock: true,
    ingredients: 'Each amber glass bottle contains a 7.75 fl oz blend of body-safe fine fragrance oils and water.',
    howToUse: [
      'To quickly freshen up a space, linens, or the inside of a closet, just use a couple spritzes.',
      'They\'re formulated to be body safe, too - so go ahead and give yourself a spritz while you\'re at it.',
      'Room & Linen Sprays last the longest when sprayed directly onto fabric.',
      'Because Room & Linen Sprays are water-based, they may not be safe for leather products. We recommend testing on an inconspicuous part of any textile first.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['7.75 fl oz', 'Body-safe water-based fragrance', 'Fine-mist nozzle', 'Amber glass bottle'],
  },
  {
    id: 'spray-ojai-lavender',
    slug: 'ojai-lavender-room-spray',
    name: 'Ojai Lavender',
    scent: 'Ojai Lavender',
    category: 'Room Spray',
    tagline: 'Aromatic, citrus, fresh',
    description: 'Sun-drenched fields, orange groves and lavender farms, jagged mountains washed in a rosy, sunset glow.',
    notes: {
      top: ['Pixie Tangerine', 'Bergamot', 'Eucalyptus'],
      middle: ['Lavender', 'Rose', 'Lily'],
      base: ['Mint', 'Red Cedar'],
    },
    imageUrl: 'https://pfcandleco.com/cdn/shop/products/RSOL.jpg',
    inStock: true,
    ingredients: 'Each amber glass bottle contains a 7.75 fl oz blend of body-safe fine fragrance oils and water.',
    howToUse: [
      'To quickly freshen up a space, linens, or the inside of a closet, just use a couple spritzes.',
      'They\'re formulated to be body safe, too - so go ahead and give yourself a spritz while you\'re at it.',
      'Room & Linen Sprays last the longest when sprayed directly onto fabric.',
      'Because Room & Linen Sprays are water-based, they may not be safe for leather products. We recommend testing on an inconspicuous part of any textile first.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['7.75 fl oz', 'Body-safe water-based fragrance', 'Fine-mist nozzle', 'Amber glass bottle'],
  },
  {
    id: 'spray-teakwood-tobacco',
    slug: 'teakwood-tobacco-room-spray',
    name: 'Teakwood & Tobacco',
    scent: 'Teakwood & Tobacco',
    category: 'Room Spray',
    tagline: 'Woody, warm, musky',
    description: 'The one that started it all. Some call it the boyfriend scent, we call it the O.G.',
    notes: {
      top: ['Orange', 'Leather'],
      middle: ['Black Tea', 'Pepper', 'Tobacco Leaf'],
      base: ['Sandalwood', 'Teak', 'Patchouli', 'Musk', 'Amber'],
    },
    imageUrl: '/images/PF Candle Co/teakwood-tobacco-spray.jpg',
    inStock: true,
    ingredients: 'Each amber glass bottle contains a 7.75 fl oz blend of body-safe fine fragrance oils and water.',
    howToUse: [
      'To quickly freshen up a space, linens, or the inside of a closet, just use a couple spritzes.',
      'They\'re formulated to be body safe, too - so go ahead and give yourself a spritz while you\'re at it.',
      'Room & Linen Sprays last the longest when sprayed directly onto fabric.',
      'Because Room & Linen Sprays are water-based, they may not be safe for leather products. We recommend testing on an inconspicuous part of any textile first.',
    ],
    scentThrow: 'Our collection is thoughtfully-crafted to enhance your atmosphere, not overpower it. We intentionally develop welcoming, non-irritating home fragrances that even the most sensitive noses can enjoy.',
    specs: ['7.75 fl oz', 'Body-safe water-based fragrance', 'Fine-mist nozzle', 'Amber glass bottle'],
  },
];

export const categories = ['Air Freshener', 'Incense', 'Candle', 'Room Spray'] as const;

export function getProductBySlug(slug: string): PFProduct | undefined {
  return pfProducts.find(p => p.slug === slug);
}
